module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,16.1,True,2023-03-30T07:00:22,,
cowidev.vax.batch.australia,0.23,False,2023-03-30T07:01:51,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 244, in main
    Australia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 216, in export
    df = self.read().pipe(self.pipeline)  # Use with attach=False
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 160, in pipeline
    .pipe(self.make_monotonic)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 19 have been NaNed for metric people_vaccinated. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-03-16']
",1 chunks of lengths 19 have been NaNed for metric people_vaccinated. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-03-16']
cowidev.vax.batch.austria_old,,,2023-03-30T07:00:06,,
cowidev.vax.batch.belgium,9.95,True,2023-03-30T07:00:16,,
cowidev.vax.batch.bolivia,4.21,True,2023-03-30T07:00:10,,
cowidev.vax.batch.canada,5.68,False,2023-03-30T07:01:56,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 282, in main
    Canada().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 270, in export
    df = df.pipe(self.pipeline, df_man)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 250, in pipeline
    .pipe(self.pipe_make_monotonic)[
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 230, in pipe_make_monotonic
    df = df.pipe(self.make_monotonic, max_removed_rows=self.max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 36 have been NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']
",1 chunks of lengths 36 have been NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']
cowidev.vax.batch.chile,0.97,True,2023-03-30T07:00:07,,
cowidev.vax.batch.czechia,31.21,True,2023-03-30T07:00:37,,
cowidev.vax.batch.denmark,0.51,False,2023-03-30T07:01:57,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/denmark.py"", line 245, in main
    Denmark().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/denmark.py"", line 226, in export
    df = self.read(index).pipe(self.pipeline, df_current).pipe(self.make_monotonic)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/denmark.py"", line 43, in read
    url = self._parse_link_zip()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/denmark.py"", line 67, in _parse_link_zip
    url = soup.find(""a"", string=""Download her"").get(""href"")
AttributeError: 'NoneType' object has no attribute 'get'
",'NoneType' object has no attribute 'get'
cowidev.vax.batch.ecdc,89.84,True,2023-03-30T07:01:36,,
cowidev.vax.batch.ecuador,,,2023-03-30T07:00:06,,
cowidev.vax.batch.estonia,0.65,True,2023-03-30T07:00:06,,
cowidev.vax.batch.france,7.95,True,2023-03-30T07:00:14,,
cowidev.vax.batch.germany,0.12,True,2023-03-30T07:00:06,,
cowidev.vax.batch.greece,16.39,True,2023-03-30T07:00:22,,
cowidev.vax.batch.hong_kong,18.37,True,2023-03-30T07:00:24,,
cowidev.vax.batch.indonesia,,,2023-03-30T07:00:06,,
cowidev.vax.batch.ireland,3.68,True,2023-03-30T07:00:09,,
cowidev.vax.batch.israel,9.77,True,2023-03-30T07:00:16,,
cowidev.vax.batch.italy,10.33,True,2023-03-30T07:00:16,,
cowidev.vax.batch.japan,36.25,True,2023-03-30T07:00:42,,
cowidev.vax.batch.jersey,5.11,True,2023-03-30T07:00:11,,
cowidev.vax.batch.latvia,69.12,True,2023-03-30T07:01:15,,
cowidev.vax.batch.lithuania,5.1,True,2023-03-30T07:00:11,,
cowidev.vax.batch.luxembourg,2.62,True,2023-03-30T07:00:08,,
cowidev.vax.batch.malaysia,0.74,True,2023-03-30T07:00:06,,
cowidev.vax.batch.malta,1.3,True,2023-03-30T07:00:07,,
cowidev.vax.batch.netherlands,,,2023-03-30T07:00:06,,
cowidev.vax.batch.new_zealand,16.86,True,2023-03-30T07:00:23,,
cowidev.vax.batch.norway,0.37,True,2023-03-30T07:00:06,,
cowidev.vax.batch.peru,4.55,True,2023-03-30T07:00:10,,
cowidev.vax.batch.portugal,,,2023-03-30T07:00:06,,
cowidev.vax.batch.romania,33.43,True,2023-03-30T07:00:39,,
cowidev.vax.batch.saudi_arabia,11.42,True,2023-03-30T07:00:17,,
cowidev.vax.batch.singapore,5.16,True,2023-03-30T07:00:11,,
cowidev.vax.batch.slovakia,53.13,True,2023-03-30T07:00:59,,
cowidev.vax.batch.slovenia,3.38,True,2023-03-30T07:00:09,,
cowidev.vax.batch.south_korea,32.36,True,2023-03-30T07:02:29,,
cowidev.vax.batch.spc,24.98,True,2023-03-30T07:00:31,,
cowidev.vax.batch.sweden,15.24,True,2023-03-30T07:00:22,,
cowidev.vax.batch.switzerland,86.16,True,2023-03-30T07:01:33,,
cowidev.vax.batch.trinidad_and_tobago,3.71,True,2023-03-30T07:00:11,,
cowidev.vax.batch.ukraine,,,2023-03-30T07:00:08,,
cowidev.vax.batch.united_kingdom,16.09,True,2023-03-30T07:00:24,,
cowidev.vax.batch.united_states,87.76,True,2023-03-30T07:01:36,,
cowidev.vax.batch.uruguay,7.84,True,2023-03-30T07:00:17,,
cowidev.vax.batch.zimbabwe,1.51,True,2023-03-30T07:00:11,,
cowidev.vax.incremental.africacdc,,,2023-03-30T07:00:10,,
cowidev.vax.incremental.antigua_barbuda,,,2023-03-30T07:00:10,,
cowidev.vax.incremental.aruba,2.57,True,2023-03-30T07:00:13,,
cowidev.vax.incremental.austria,,,2023-03-30T07:00:10,,
cowidev.vax.incremental.azerbaijan,,,2023-03-30T07:00:10,,
cowidev.vax.incremental.bahrain,,,2023-03-30T07:00:10,,
cowidev.vax.incremental.bangladesh,38.41,False,2023-03-30T07:03:08,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 443, in _error_catcher
    yield
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 815, in read_chunked
    self._update_chunk_length()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 745, in _update_chunk_length
    line = self._fp.fp.readline()
  File ""/usr/lib/python3.10/socket.py"", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/models.py"", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 623, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 803, in read_chunked
    with self._error_catcher():
  File ""/usr/lib/python3.10/contextlib.py"", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 448, in _error_catcher
    raise ReadTimeoutError(self._pool, None, ""Read timed out."")
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='103.247.238.92', port=80): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 112, in main
    Bangladesh().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 98, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 25, in read
    metrics = self._parse_metrics(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 74, in _parse_metrics
    single_doses = self._parse_single_doses()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 38, in _parse_single_doses
    soup = get_soup(url, timeout=30)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 687, in send
    r.content
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/models.py"", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/models.py"", line 767, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='103.247.238.92', port=80): Read timed out.
","HTTPConnectionPool(host='103.247.238.92', port=80): Read timed out."
cowidev.vax.incremental.barbados,,,2023-03-30T07:00:11,,
cowidev.vax.incremental.brazil,2.1,True,2023-03-30T07:00:13,,
cowidev.vax.incremental.bulgaria,10.53,True,2023-03-30T07:00:21,,
cowidev.vax.incremental.china,17.75,True,2023-03-30T07:00:29,,
cowidev.vax.incremental.costa_rica,,,2023-03-30T07:00:11,,
cowidev.vax.incremental.croatia,2.07,True,2023-03-30T07:00:13,,
cowidev.vax.incremental.cuba,11.43,True,2023-03-30T07:00:22,,
cowidev.vax.incremental.curacao,1.35,True,2023-03-30T07:00:14,,
cowidev.vax.incremental.cyprus,2.66,True,2023-03-30T07:00:16,,
cowidev.vax.incremental.dominican_republic,11.41,False,2023-03-30T07:03:19,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 113, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 92, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 82, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,10.02,True,2023-03-30T07:00:24,,
cowidev.vax.incremental.faeroe_islands,1.31,True,2023-03-30T07:00:15,,
cowidev.vax.incremental.fiji,0.0,True,2023-03-30T07:00:15,,
cowidev.vax.incremental.finland,0.59,True,2023-03-30T07:00:16,,
cowidev.vax.incremental.gabon,,,2023-03-30T07:00:16,,
cowidev.vax.incremental.georgia,7.79,True,2023-03-30T07:00:23,,
cowidev.vax.incremental.greenland,0.64,False,2023-03-30T07:03:20,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 76, in main
    Greenland().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 63, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 17, in read
    data = self._parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 21, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 31, in _parse_data_metrics
    assert len(counter_1) == len(counter_2) == 1
AssertionError
",
cowidev.vax.incremental.guatemala,,,2023-03-30T07:00:16,,
cowidev.vax.incremental.guernsey,8.76,True,2023-03-30T07:00:24,,
cowidev.vax.incremental.hungary,79.28,True,2023-03-30T07:01:35,,
cowidev.vax.incremental.iceland,2.96,True,2023-03-30T07:00:19,,
cowidev.vax.incremental.india,5.27,True,2023-03-30T07:00:22,,
cowidev.vax.incremental.iran,,,2023-03-30T07:00:17,,
cowidev.vax.incremental.isle_of_man,2.7,True,2023-03-30T07:00:20,,
cowidev.vax.incremental.jamaica,7.3,True,2023-03-30T07:00:25,,
cowidev.vax.incremental.kazakhstan,6.71,True,2023-03-30T07:00:26,,
cowidev.vax.incremental.kosovo,3.16,False,2023-03-30T07:03:23,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 82, in main
    Kosovo().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 22, in read
    soup = get_soup(self.source_url, verify=False)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://msh.rks-gov.net/sq/statistikat-covid-19/ not reached! Error code 404 Not Found
",Source https://msh.rks-gov.net/sq/statistikat-covid-19/ not reached! Error code 404 Not Found
cowidev.vax.incremental.kyrgyzstan,3.95,True,2023-03-30T07:00:25,,
cowidev.vax.incremental.laos,1.69,True,2023-03-30T07:03:24,,
cowidev.vax.incremental.macao,23.86,True,2023-03-30T07:00:46,,
cowidev.vax.incremental.moldova,,,2023-03-30T07:00:22,,
cowidev.vax.incremental.monaco,79.91,True,2023-03-30T07:01:42,,
cowidev.vax.incremental.mongolia,1.38,True,2023-03-30T07:00:24,,
cowidev.vax.incremental.montenegro,0.69,True,2023-03-30T07:00:23,,
cowidev.vax.incremental.morocco,,,2023-03-30T07:00:22,,
cowidev.vax.incremental.myanmar,,,2023-03-30T07:00:22,,
cowidev.vax.incremental.nepal,,,2023-03-30T07:00:22,,
cowidev.vax.incremental.north_macedonia,,,2023-03-30T07:00:22,,
cowidev.vax.incremental.northern_cyprus,2.82,True,2023-03-30T07:00:25,,
cowidev.vax.incremental.paho,82.0,False,2023-03-30T07:04:46,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 167, in pipeline
    df.pipe(self.pipe_check_columns)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 122, in pipe_check_columns
    raise ValueError(f""Missing column fields: {columns_missing}. Present columns are: {df.columns}"")
ValueError: Missing column fields: {'Second dose', 'Single dose', 'Country/ Territory', '1st additional dose', 'Country code', '2nd additional dose', 'First dose', 'Total doses'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')
","Missing column fields: {'Second dose', 'Single dose', 'Country/ Territory', '1st additional dose', 'Country code', '2nd additional dose', 'First dose', 'Total doses'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')"
cowidev.vax.incremental.pakistan,,,2023-03-30T07:00:23,,
cowidev.vax.incremental.philippines,,,2023-03-30T07:00:23,,
cowidev.vax.incremental.poland,1.37,True,2023-03-30T07:00:24,,
cowidev.vax.incremental.qatar,,,2023-03-30T07:00:23,,
cowidev.vax.incremental.russia,16.81,True,2023-03-30T07:00:40,,
cowidev.vax.incremental.saint_lucia,,,2023-03-30T07:00:24,,
cowidev.vax.incremental.serbia,10.72,True,2023-03-30T07:00:34,,
cowidev.vax.incremental.south_africa,,,2023-03-30T07:00:24,,
cowidev.vax.incremental.spain,14.87,True,2023-03-30T07:00:38,,
cowidev.vax.incremental.sri_lanka,,,2023-03-30T07:00:24,,
cowidev.vax.incremental.suriname,14.67,True,2023-03-30T07:00:38,,
cowidev.vax.incremental.taiwan,8.78,False,2023-03-30T07:04:55,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 179, in main
    Taiwan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 165, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 35, in read
    df = self._parse_table(url_pdf)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 62, in _parse_table
    raise ValueError(f""Table 1: format has changed! It has shape {df.shape} instead of {shape_expected}"")
ValueError: Table 1: format has changed! It has shape (42, 4) instead of (39, 4)
","Table 1: format has changed! It has shape (42, 4) instead of (39, 4)"
cowidev.vax.incremental.thailand,6.55,True,2023-03-30T07:00:31,,
cowidev.vax.incremental.turkey,6.24,False,2023-03-30T07:05:01,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://covid19asi.saglik.gov.tr/ not reached! Error code 504 Gateway Timeout
",Source https://covid19asi.saglik.gov.tr/ not reached! Error code 504 Gateway Timeout
cowidev.vax.incremental.united_arab_emirates,,,2023-03-30T07:00:24,,
cowidev.vax.incremental.vietnam,,,2023-03-30T07:00:24,,
cowidev.vax.incremental.who,33.62,True,2023-03-30T07:00:58,,
cowidev.vax.incremental.zambia,0.91,True,2023-03-30T07:00:26,,
