module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,11.65,True,2023-03-02T07:00:17,,
cowidev.vax.batch.australia,0.4,False,2023-03-02T07:03:13,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 244, in main
    Australia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 216, in export
    df = self.read().pipe(self.pipeline)  # Use with attach=False
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 160, in pipeline
    .pipe(self.make_monotonic)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 12 have been NaNed for metric people_fully_vaccinated. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-02-02']
",1 chunks of lengths 12 have been NaNed for metric people_fully_vaccinated. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-02-02']
cowidev.vax.batch.austria,11.47,True,2023-03-02T07:00:17,,
cowidev.vax.batch.belgium,9.62,True,2023-03-02T07:00:15,,
cowidev.vax.batch.bolivia,4.36,True,2023-03-02T07:00:10,,
cowidev.vax.batch.canada,8.9,False,2023-03-02T07:03:22,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 282, in main
    Canada().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 270, in export
    df = df.pipe(self.pipeline, df_man)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 250, in pipeline
    .pipe(self.pipe_make_monotonic)[
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 230, in pipe_make_monotonic
    df = df.pipe(self.make_monotonic, max_removed_rows=self.max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 36 have been NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']
",1 chunks of lengths 36 have been NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']
cowidev.vax.batch.chile,0.89,True,2023-03-02T07:00:06,,
cowidev.vax.batch.czechia,2.5,False,2023-03-02T07:03:25,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 186, in main
    Czechia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 171, in export
    base = read(self.source_url).pipe(base_pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 69, in base_pipeline
    return df.pipe(check_vaccine_names).pipe(translate_vaccine_names)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 48, in check_vaccine_names
    raise ValueError(""Found unknown vaccines: {}"".format(unknown_vaccines))
ValueError: Found unknown vaccines: {'Valneva', 'Comirnaty 6m-4', 'SPIKEVAX BIVALENT ORIGINAL/OMICRON BA.4-5', 'Covovax', 'Sputnik V'}
","Found unknown vaccines: {'Valneva', 'Comirnaty 6m-4', 'SPIKEVAX BIVALENT ORIGINAL/OMICRON BA.4-5', 'Covovax', 'Sputnik V'}"
cowidev.vax.batch.denmark,87.24,True,2023-03-02T07:01:33,,
cowidev.vax.batch.ecdc,91.51,True,2023-03-02T07:01:37,,
cowidev.vax.batch.ecuador,,,2023-03-02T07:00:06,,
cowidev.vax.batch.estonia,0.66,True,2023-03-02T07:00:06,,
cowidev.vax.batch.france,6.73,True,2023-03-02T07:00:12,,
cowidev.vax.batch.germany,3.2,True,2023-03-02T07:00:09,,
cowidev.vax.batch.greece,13.98,True,2023-03-02T07:00:20,,
cowidev.vax.batch.hong_kong,16.17,True,2023-03-02T07:00:22,,
cowidev.vax.batch.indonesia,,,2023-03-02T07:00:06,,
cowidev.vax.batch.ireland,4.51,True,2023-03-02T07:00:10,,
cowidev.vax.batch.israel,10.53,True,2023-03-02T07:00:16,,
cowidev.vax.batch.italy,9.95,True,2023-03-02T07:00:16,,
cowidev.vax.batch.japan,35.03,True,2023-03-02T07:00:41,,
cowidev.vax.batch.jersey,4.39,True,2023-03-02T07:00:10,,
cowidev.vax.batch.latvia,64.73,True,2023-03-02T07:01:10,,
cowidev.vax.batch.lithuania,9.11,True,2023-03-02T07:00:15,,
cowidev.vax.batch.luxembourg,2.68,True,2023-03-02T07:00:08,,
cowidev.vax.batch.malaysia,0.63,True,2023-03-02T07:00:06,,
cowidev.vax.batch.malta,1.38,True,2023-03-02T07:00:07,,
cowidev.vax.batch.netherlands,,,2023-03-02T07:00:06,,
cowidev.vax.batch.new_zealand,10.28,True,2023-03-02T07:00:16,,
cowidev.vax.batch.norway,0.47,True,2023-03-02T07:00:06,,
cowidev.vax.batch.peru,4.73,True,2023-03-02T07:00:10,,
cowidev.vax.batch.portugal,,,2023-03-02T07:00:06,,
cowidev.vax.batch.romania,25.17,True,2023-03-02T07:00:31,,
cowidev.vax.batch.saudi_arabia,11.46,True,2023-03-02T07:00:17,,
cowidev.vax.batch.singapore,4.63,True,2023-03-02T07:00:10,,
cowidev.vax.batch.slovakia,62.98,True,2023-03-02T07:01:09,,
cowidev.vax.batch.slovenia,2.9,True,2023-03-02T07:00:09,,
cowidev.vax.batch.south_korea,88.7,True,2023-03-02T07:01:35,,
cowidev.vax.batch.spc,22.16,True,2023-03-02T07:00:29,,
cowidev.vax.batch.sweden,12.96,True,2023-03-02T07:00:20,,
cowidev.vax.batch.switzerland,88.03,True,2023-03-02T07:01:36,,
cowidev.vax.batch.trinidad_and_tobago,2.61,True,2023-03-02T07:00:11,,
cowidev.vax.batch.ukraine,,,2023-03-02T07:00:09,,
cowidev.vax.batch.united_kingdom,13.41,True,2023-03-02T07:00:22,,
cowidev.vax.batch.united_states,88.9,True,2023-03-02T07:01:38,,
cowidev.vax.batch.uruguay,7.38,True,2023-03-02T07:00:17,,
cowidev.vax.batch.zimbabwe,2.35,True,2023-03-02T07:00:12,,
cowidev.vax.incremental.africacdc,,,2023-03-02T07:00:10,,
cowidev.vax.incremental.antigua_barbuda,,,2023-03-02T07:00:10,,
cowidev.vax.incremental.aruba,1.85,True,2023-03-02T07:00:12,,
cowidev.vax.incremental.azerbaijan,,,2023-03-02T07:00:10,,
cowidev.vax.incremental.bahrain,,,2023-03-02T07:00:10,,
cowidev.vax.incremental.bangladesh,59.19,True,2023-03-02T07:01:09,,
cowidev.vax.incremental.barbados,,,2023-03-02T07:00:10,,
cowidev.vax.incremental.brazil,0.98,True,2023-03-02T07:00:11,,
cowidev.vax.incremental.bulgaria,8.75,True,2023-03-02T07:00:20,,
cowidev.vax.incremental.china,20.9,True,2023-03-02T07:00:32,,
cowidev.vax.incremental.costa_rica,,,2023-03-02T07:00:12,,
cowidev.vax.incremental.croatia,2.77,True,2023-03-02T07:00:15,,
cowidev.vax.incremental.cuba,8.81,True,2023-03-02T07:00:21,,
cowidev.vax.incremental.curacao,2.15,True,2023-03-02T07:00:14,,
cowidev.vax.incremental.cyprus,1.8,True,2023-03-02T07:00:16,,
cowidev.vax.incremental.dominican_republic,22.65,False,2023-03-02T07:03:47,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 113, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 92, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 82, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,8.96,True,2023-03-02T07:00:24,,
cowidev.vax.incremental.faeroe_islands,1.18,True,2023-03-02T07:00:16,,
cowidev.vax.incremental.fiji,0.0,True,2023-03-02T07:00:16,,
cowidev.vax.incremental.finland,0.82,True,2023-03-02T07:00:16,,
cowidev.vax.incremental.gabon,,,2023-03-02T07:00:16,,
cowidev.vax.incremental.georgia,4.82,True,2023-03-02T07:00:21,,
cowidev.vax.incremental.greenland,0.17,False,2023-03-02T07:03:48,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 76, in main
    Greenland().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 63, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 17, in read
    data = self._parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 21, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 31, in _parse_data_metrics
    assert len(counter_1) == len(counter_2) == 1
AssertionError
",
cowidev.vax.incremental.guatemala,,,2023-03-02T07:00:16,,
cowidev.vax.incremental.guernsey,6.63,True,2023-03-02T07:00:23,,
cowidev.vax.incremental.hungary,80.2,True,2023-03-02T07:01:37,,
cowidev.vax.incremental.iceland,1.48,True,2023-03-02T07:00:18,,
cowidev.vax.incremental.india,4.74,True,2023-03-02T07:00:22,,
cowidev.vax.incremental.iran,,,2023-03-02T07:00:17,,
cowidev.vax.incremental.isle_of_man,2.63,True,2023-03-02T07:00:20,,
cowidev.vax.incremental.jamaica,8.53,True,2023-03-02T07:00:26,,
cowidev.vax.incremental.kazakhstan,8.61,True,2023-03-02T07:00:26,,
cowidev.vax.incremental.kosovo,0.55,False,2023-03-02T07:03:48,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 82, in main
    Kosovo().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 22, in read
    soup = get_soup(self.source_url, verify=False)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://msh.rks-gov.net/sq/statistikat-covid-19/ not reached! Error code 404 Not Found
",Source https://msh.rks-gov.net/sq/statistikat-covid-19/ not reached! Error code 404 Not Found
cowidev.vax.incremental.kyrgyzstan,3.77,True,2023-03-02T07:00:22,,
cowidev.vax.incremental.laos,6.5,True,2023-03-02T07:00:26,,
cowidev.vax.incremental.macao,12.12,True,2023-03-02T07:00:32,,
cowidev.vax.incremental.moldova,,,2023-03-02T07:00:20,,
cowidev.vax.incremental.monaco,86.58,True,2023-03-02T07:01:46,,
cowidev.vax.incremental.mongolia,1.17,True,2023-03-02T07:00:21,,
cowidev.vax.incremental.montenegro,0.93,True,2023-03-02T07:00:21,,
cowidev.vax.incremental.morocco,,,2023-03-02T07:00:21,,
cowidev.vax.incremental.myanmar,,,2023-03-02T07:00:21,,
cowidev.vax.incremental.nepal,,,2023-03-02T07:00:21,,
cowidev.vax.incremental.north_macedonia,,,2023-03-02T07:00:21,,
cowidev.vax.incremental.northern_cyprus,5.23,True,2023-03-02T07:00:26,,
cowidev.vax.incremental.paho,136.78,False,2023-03-02T07:06:05,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 64, in _parse_data
    filename = self._get_downloaded_filename()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 116, in _get_downloaded_filename
    return max(files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
",max() arg is an empty sequence
cowidev.vax.incremental.pakistan,,,2023-03-02T07:00:21,,
cowidev.vax.incremental.philippines,,,2023-03-02T07:00:21,,
cowidev.vax.incremental.poland,1.36,True,2023-03-02T07:00:22,,
cowidev.vax.incremental.qatar,,,2023-03-02T07:00:21,,
cowidev.vax.incremental.russia,13.35,True,2023-03-02T07:00:34,,
cowidev.vax.incremental.saint_lucia,,,2023-03-02T07:00:22,,
cowidev.vax.incremental.serbia,6.8,True,2023-03-02T07:00:29,,
cowidev.vax.incremental.south_africa,,,2023-03-02T07:00:22,,
cowidev.vax.incremental.spain,47.97,True,2023-03-02T07:01:10,,
cowidev.vax.incremental.sri_lanka,,,2023-03-02T07:00:22,,
cowidev.vax.incremental.suriname,14.39,True,2023-03-02T07:00:37,,
cowidev.vax.incremental.taiwan,17.09,True,2023-03-02T07:00:39,,
cowidev.vax.incremental.thailand,6.08,True,2023-03-02T07:00:28,,
cowidev.vax.incremental.turkey,18.38,False,2023-03-02T07:06:23,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 449, in _make_request
    six.raise_from(e, None)
  File ""<string>"", line 3, in raise_from
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 444, in _make_request
    httplib_response = conn.getresponse()
  File ""/usr/lib/python3.10/http/client.py"", line 1374, in getresponse
    response.begin()
  File ""/usr/lib/python3.10/http/client.py"", line 318, in begin
    version, status, reason = self._read_status()
  File ""/usr/lib/python3.10/http/client.py"", line 287, in _read_status
    raise RemoteDisconnected(""Remote end closed connection without""
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/packages/six.py"", line 769, in reraise
    raise value.with_traceback(tb)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 449, in _make_request
    six.raise_from(e, None)
  File ""<string>"", line 3, in raise_from
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 444, in _make_request
    httplib_response = conn.getresponse()
  File ""/usr/lib/python3.10/http/client.py"", line 1374, in getresponse
    response.begin()
  File ""/usr/lib/python3.10/http/client.py"", line 318, in begin
    version, status, reason = self._read_status()
  File ""/usr/lib/python3.10/http/client.py"", line 287, in _read_status
    raise RemoteDisconnected(""Remote end closed connection without""
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
cowidev.vax.incremental.united_arab_emirates,,,2023-03-02T07:00:24,,
cowidev.vax.incremental.vietnam,,,2023-03-02T07:00:24,,
cowidev.vax.incremental.who,36.01,True,2023-03-02T07:01:00,,
cowidev.vax.incremental.zambia,0.97,True,2023-03-02T07:00:27,,
